// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/zhedevops/shortlink/internal/model"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckIDByURL mocks base method.
func (m *MockRepository) CheckIDByURL(url string) model.Shorty {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIDByURL", url)
	ret0, _ := ret[0].(model.Shorty)
	return ret0
}

// CheckIDByURL indicates an expected call of CheckIDByURL.
func (mr *MockRepositoryMockRecorder) CheckIDByURL(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIDByURL", reflect.TypeOf((*MockRepository)(nil).CheckIDByURL), url)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser() (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser")
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser))
}

// GetOriginalURL mocks base method.
func (m *MockRepository) GetOriginalURL(id string) model.Shorty {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", id)
	ret0, _ := ret[0].(model.Shorty)
	return ret0
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockRepositoryMockRecorder) GetOriginalURL(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockRepository)(nil).GetOriginalURL), id)
}

// GetShortysByUser mocks base method.
func (m *MockRepository) GetShortysByUser(userID uint32) ([]*model.Shorty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortysByUser", userID)
	ret0, _ := ret[0].([]*model.Shorty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortysByUser indicates an expected call of GetShortysByUser.
func (mr *MockRepositoryMockRecorder) GetShortysByUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortysByUser", reflect.TypeOf((*MockRepository)(nil).GetShortysByUser), userID)
}

// Ping mocks base method.
func (m *MockRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping), ctx)
}

// SetShortURL mocks base method.
func (m *MockRepository) SetShortURL(shortys *model.Shorty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetShortURL", shortys)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetShortURL indicates an expected call of SetShortURL.
func (mr *MockRepositoryMockRecorder) SetShortURL(shortys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShortURL", reflect.TypeOf((*MockRepository)(nil).SetShortURL), shortys)
}
